import React, { useCallback, useEffect, useState } from "react";
import { Alert, Badge, Button, Card, CardBody, CardHeader, Col, Input, Row, Spinner, Table } from "reactstrap";
import { Link, useNavigate } from "react-router-dom";
import Breadcrumbs from "../../components/Common/Breadcrumb.jsx";
import Paginations from "../../components/Common/Paginations.jsx";
import { useAuth } from "../../context/AuthContext.jsx";
import { archiveDynamicReport, deleteDynamicReport, duplicateDynamicReport, getDynamicReports, getSources, restoreDynamicReport } from "../../services/dynamicReportService.jsx";

const DynamicReportList = () => {
  document.title = "گزارش‌ساز پویا | داشبورد آیسوق";
  const { hasPermission } = useAuth(); const navigate = useNavigate();
  const [items, setItems] = useState([]); const [sources, setSources] = useState([]); const [meta, setMeta] = useState({ page: 1, limit: 20, total: 0 });
  const [filters, setFilters] = useState({ search: "", sourceId: "", status: "" }); const [debounced, setDebounced] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const timer = setTimeout(() => setDebounced(filters.search), 350); return () => clearTimeout(timer); }, [filters.search]);
  const load = useCallback(async (page = meta.page) => { setLoading(true); setError(""); try { const res = await getDynamicReports({ page, limit: Math.min(100, meta.limit), search: debounced || undefined, sourceId: filters.sourceId || undefined, status: filters.status || undefined }); setItems(res.items); setMeta(res.pagination); } catch (e) { setError(e?.response?.status === 403 ? "شما اجازه مشاهده گزارش‌های پویا را ندارید." : "دریافت فهرست گزارش‌ها ناموفق بود."); } finally { setLoading(false); } }, [debounced, filters.sourceId, filters.status, meta.limit, meta.page]);
  useEffect(() => { getSources().then((data) => setSources(data?.items || data || [])).catch(() => {}); }, []);
  useEffect(() => { load(1); }, [debounced, filters.sourceId, filters.status]); // eslint-disable-line react-hooks/exhaustive-deps
  const action = async (fn, item, confirmText) => { if (confirmText && !window.confirm(confirmText)) return; await fn(item.id); await load(meta.page); };
  return <div className="page-content"><div className="container-fluid"><Breadcrumbs title="گزارش‌ها" breadcrumbItem="گزارش‌ساز پویا" /><Card><CardHeader className="d-flex justify-content-between align-items-center"><h4 className="card-title mb-0">گزارش‌های پویا</h4>{hasPermission("dynamic-reports.create") && <Button color="primary" onClick={() => navigate("/dynamic-reports/create")}>ساخت گزارش</Button>}</CardHeader><CardBody>
    <Row className="g-2 mb-3"><Col md={6}><Input value={filters.search} onChange={(e) => setFilters((v) => ({ ...v, search: e.target.value }))} placeholder="جست‌وجوی نام گزارش" aria-label="جست‌وجوی گزارش" /></Col><Col md={3}><Input type="select" value={filters.sourceId} onChange={(e) => setFilters((v) => ({ ...v, sourceId: e.target.value }))}><option value="">همه منابع</option>{sources.map((s) => <option key={s.id} value={s.id}>{s.label || s.name}</option>)}</Input></Col><Col md={3}><Input type="select" value={filters.status} onChange={(e) => setFilters((v) => ({ ...v, status: e.target.value }))}><option value="">همه وضعیت‌ها</option><option value="draft">پیش‌نویس</option><option value="active">فعال</option><option value="archived">بایگانی‌شده</option></Input></Col></Row>
    {error && <Alert color="danger">{error}</Alert>}{loading ? <div className="text-center py-5"><Spinner /></div> : <div className="table-responsive"><Table hover><thead><tr><th>نام</th><th>منبع</th><th>وضعیت</th><th>آخرین تغییر</th><th>عملیات</th></tr></thead><tbody>{items.length ? items.map((item) => <tr key={item.id}><td>{hasPermission("dynamic-reports.show") ? <Link to={`/dynamic-reports/${item.id}`}>{item.name}</Link> : item.name}</td><td>{item.sourceLabel || sources.find((x) => x.id === item.sourceId)?.label || item.sourceId}</td><td><Badge color={item.status === "active" ? "success" : item.status === "archived" ? "secondary" : "warning"}>{item.statusLabel || item.status}</Badge></td><td>{item.updatedAt ? new Intl.DateTimeFormat("fa-IR-u-ca-persian", { dateStyle: "medium", timeZone: "Asia/Tehran" }).format(new Date(item.updatedAt)) : "—"}</td><td className="text-nowrap">{hasPermission("dynamic-reports.update") && item.status !== "archived" && <Button size="sm" color="light" className="ms-1" onClick={() => navigate(`/dynamic-reports/${item.id}/edit`)}>ویرایش</Button>}{hasPermission("dynamic-reports.create") && <Button size="sm" color="light" className="ms-1" onClick={() => action(duplicateDynamicReport, item)}>کپی</Button>}{hasPermission("dynamic-reports.update") && <Button size="sm" color="light" className="ms-1" onClick={() => action(item.status === "archived" ? restoreDynamicReport : archiveDynamicReport, item, item.status === "archived" ? null : "گزارش بایگانی شود؟")}>{item.status === "archived" ? "بازیابی" : "بایگانی"}</Button>}{hasPermission("dynamic-reports.delete") && <Button size="sm" color="danger" outline onClick={() => action(deleteDynamicReport, item, "آیا از حذف این گزارش مطمئن هستید؟")}>حذف</Button>}</td></tr>) : <tr><td colSpan="5" className="text-center text-muted py-4">گزارشی یافت نشد.</td></tr>}</tbody></Table></div>}
    <Paginations perPageData={meta.limit} data={items} totalRecords={meta.total} currentPage={meta.page} setCurrentPage={load} isShowingPageLength paginationDiv="col-sm-auto" paginationClass="pagination pagination-sm mb-0" />
  </CardBody></Card></div></div>;
};
export default DynamicReportList;
