import React, { useEffect, useState } from "react";
import { Alert, Button, Card, CardBody, CardHeader, Progress, Spinner } from "reactstrap";
import { useParams } from "react-router-dom";
import Breadcrumbs from "../../components/Common/Breadcrumb.jsx";
import { useAuth } from "../../context/AuthContext.jsx";
import { executeDynamicReport, exportDynamicReport, getDynamicReport, getVisualizations } from "../../services/dynamicReportService.jsx";
import GenericResultTable from "./GenericResultTable.jsx";
import VisualizationRenderer from "./VisualizationRenderer.jsx";
const filenameFrom = (headers, fallback) => { const raw = headers?.["content-disposition"] || ""; const utf = raw.match(/filename\*=UTF-8''([^;]+)/i); const plain = raw.match(/filename="?([^";]+)"?/i); return decodeURIComponent(utf?.[1] || plain?.[1] || fallback); };
const DynamicReportView = () => {
  const { id } = useParams(); const { hasPermission } = useAuth(); const [report, setReport] = useState(null); const [result, setResult] = useState(null); const [allowed, setAllowed] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [progress, setProgress] = useState(0);
  useEffect(() => { Promise.all([getDynamicReport(id), getVisualizations()]).then(([r, v]) => { setReport(r); setAllowed(v?.items || v || []); }).catch((e) => setError(e?.response?.status === 404 ? "گزارش یافت نشد." : e?.response?.status === 403 ? "اجازه مشاهده این گزارش را ندارید." : "دریافت گزارش ناموفق بود.")).finally(() => setLoading(false)); }, [id]);
  const execute = async (nextPage = page, nextSearch = search) => { setLoading(true); setError(""); try { setResult(await executeDynamicReport(id, { page: nextPage, limit: 100, search: nextSearch || undefined })); setPage(nextPage); } catch (e) { const body = e?.response?.data?.data || e?.response?.data; setError(e?.code === "ECONNABORTED" ? "زمان پاسخ سرور به پایان رسید." : body?.message || "اجرای گزارش ناموفق بود."); } finally { setLoading(false); } };
  const exportExcel = async () => { setProgress(1); try { const res = await exportDynamicReport(id, { search: search || undefined }, (e) => e.total && setProgress(Math.min(99, Math.round(e.loaded / e.total * 100)))); const url = URL.createObjectURL(res.data); const link = document.createElement("a"); link.href = url; link.download = filenameFrom(res.headers, `report-${id}.xlsx`); document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); setProgress(100); } catch (e) { setError(e?.response?.data?.message || "دریافت فایل Excel ناموفق بود."); } finally { setTimeout(() => setProgress(0), 1000); } };
  if (!report && loading) return <div className="page-content text-center py-5"><Spinner /></div>;
  return <div className="page-content"><div className="container-fluid"><Breadcrumbs title="گزارش‌ساز پویا" breadcrumbItem={report?.name || "گزارش"} />{error && <Alert color="danger">{error}</Alert>}<Card><CardHeader className="d-flex justify-content-between align-items-center"><div><h4 className="mb-1">{report?.name}</h4><div className="text-muted">{report?.description}</div></div><div>{hasPermission("dynamic-reports.execute") && <Button color="primary" className="ms-2" onClick={() => execute(1, search)}>اجرای گزارش</Button>}{hasPermission("dynamic-reports.export") && result && <Button color="success" onClick={exportExcel}>دانلود Excel</Button>}</div></CardHeader><CardBody>{progress > 0 && <Progress value={progress} className="mb-3">{progress}%</Progress>}{result?.warnings?.map((w, i) => <Alert color="warning" key={i}>{w}</Alert>)}<VisualizationRenderer visualization={result?.visualization} allowed={allowed} /><GenericResultTable result={result} loading={loading} error="" page={page} limit={100} search={search} onSearch={setSearch} onPage={(nextPage) => execute(nextPage, search)} />{result && <div className="mt-2"><Button size="sm" color="light" onClick={() => execute(1, search)}>اعمال جست‌وجو روی سرور</Button></div>}{result?.execution?.truncated && <Alert color="warning" className="mt-3">نتیجه به دلیل محدودیت حجم کوتاه شده است.</Alert>}</CardBody></Card></div></div>;
};
export default DynamicReportView;
