import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Button, Card, CardBody, CardHeader, Col, Input, Label, Row } from "reactstrap";
import { useParams, useSearchParams } from "react-router-dom";
import Breadcrumbs from "../../components/Common/Breadcrumb.jsx";
import Paginations from "../../components/Common/Paginations.jsx";
import Can from "../../components/Access/Can.jsx";
import { exportImportLogRows, getImportLog, getImportLogRows, saveBlob } from "../../services/importLogService.jsx";
import { DataModal, ErrorBox, faDate, faNumber, LoadingRows, StatusBadge, Summary } from "./ImportLogComponents.jsx";
import { errorState, formatData, isActiveStatus, mergeQuery, paramsToObject, ROW_FILTER_KEYS } from "./importLogUtils.js";
import useVisiblePolling from "./useVisiblePolling.js";

const ImportLogDetail = () => {
  document.title = "جزئیات لاگ ورود اطلاعات | داشبورد آیسوق";
  const { id } = useParams(); const [query, setQuery] = useSearchParams(); const [log, setLog] = useState(null); const [items, setItems] = useState([]); const [meta, setMeta] = useState({ page: 1, limit: 20, total: 0, lastPage: 1 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [selectedData, setSelectedData] = useState(undefined); const [draft, setDraft] = useState(query.get("search") || ""); const [exporting, setExporting] = useState(false); const controller = useRef(); const signature = query.toString();
  const update = useCallback((changes, reset = true) => setQuery((current) => mergeQuery(current, changes, reset), { replace: true }), [setQuery]);
  const load = useCallback(async () => { controller.current?.abort(); const abort = new AbortController(); controller.current = abort; setLoading(true); setError(null); const params = paramsToObject(new URLSearchParams(window.location.search), ROW_FILTER_KEYS); try { const [detail, rows] = await Promise.all([getImportLog(id, params.schoolId, abort.signal), getImportLogRows(id, params, abort.signal)]); setLog(rows.importLog || detail); setItems(rows.items); setMeta(rows.pagination); } catch (e) { if (e?.code !== "ERR_CANCELED") { setError(errorState(e, true)); setItems([]); } } finally { if (!abort.signal.aborted) setLoading(false); } }, [id]);
  useEffect(() => { load(); return () => controller.current?.abort(); }, [signature, load]);
  useEffect(() => { const timer = setTimeout(() => { if ((query.get("search") || "") !== draft) update({ search: draft }); }, 400); return () => clearTimeout(timer); }, [draft]); // eslint-disable-line react-hooks/exhaustive-deps
  const active = useMemo(() => isActiveStatus(log?.status), [log]);
  useVisiblePolling(load, active);
  const doExport = async () => { setExporting(true); try { const params = paramsToObject(query, ROW_FILTER_KEYS.filter((key) => !["page", "limit"].includes(key))); saveBlob(await exportImportLogRows(id, params)); } finally { setExporting(false); } };
  return <div className="page-content"><div className="container-fluid"><Breadcrumbs title="لاگ ورود اطلاعات" breadcrumbItem="جزئیات" /><ErrorBox error={error} onRetry={load} />
    {loading && !log ? <LoadingRows /> : log && <><Card className="mb-3"><CardHeader><h5 className="mb-0">خلاصه import #{faNumber(log.id)}</h5></CardHeader><CardBody><Summary item={log} /></CardBody></Card>
    <Card className="mb-3"><CardHeader><h5 className="mb-0">فیلتر ردیف‌ها</h5></CardHeader><CardBody><Row className="g-3"><Col md="4"><Label>جست‌وجو</Label><Input value={draft} onChange={(e) => setDraft(e.target.value)} /></Col><Col md="2"><Label>وضعیت</Label><Input type="select" value={query.get("status") || ""} onChange={(e) => update({ status: e.target.value })}><option value="">همه</option><option value="success">موفق</option><option value="failed">ناموفق</option></Input></Col><Col md="2"><Label>عملیات</Label><Input value={query.get("action") || ""} onChange={(e) => update({ action: e.target.value })} /></Col><Col md="2"><Label>شماره ردیف</Label><Input inputMode="numeric" value={query.get("rowNumber") || ""} onChange={(e) => update({ rowNumber: e.target.value.replace(/\D/g, "") })} /></Col><Col className="d-flex align-items-end"><Can permission="import-logs.export"><Button color="success" disabled={exporting} onClick={doExport}>{exporting ? "در حال دریافت…" : "خروجی Excel"}</Button></Can></Col></Row></CardBody></Card>
    <Card><CardHeader className="d-flex justify-content-between"><h5 className="mb-0">ردیف‌ها</h5><span>{faNumber(meta.total)} رکورد</span></CardHeader><CardBody>{loading ? <LoadingRows /> : !error && !items.length ? <div className="text-center text-muted py-5">ردیفی مطابق فیلترها یافت نشد.</div> : <div className="table-responsive"><table className="table table-bordered table-hover align-middle"><thead><tr>{[["rowNumber","شماره ردیف"],["status","وضعیت"],["action","عملیات"],["errorMessage","پیام خطا"],["data","داده"],["createdAt","زمان"]].map(([key,label]) => <th role="button" key={key} onClick={() => update({ sortBy: key, sortOrder: query.get("sortBy") === key && query.get("sortOrder") !== "DESC" ? "DESC" : "ASC" })}>{label}</th>)}<th>مشاهده</th></tr></thead><tbody>{items.map((item) => { const data = formatData(item.data); return <tr key={item.id}><td>{faNumber(item.rowNumber)}</td><td><StatusBadge status={item.status} /></td><td>{item.action || "—"}</td><td className="text-danger" style={{ maxWidth: 300, whiteSpace: "pre-wrap" }}>{item.errorMessage ? String(item.errorMessage) : "—"}</td><td><span dir="ltr" className="d-inline-block text-truncate" style={{ maxWidth: 250 }}>{data}</span></td><td>{faDate(item.createdAt)}</td><td><Button size="sm" color="primary" onClick={() => setSelectedData(item.data)}>نمایش داده</Button></td></tr>; })}</tbody></table></div>}{!loading && !error && <Paginations perPageData={meta.limit} data={items} totalRecords={meta.total} currentPage={meta.page} setCurrentPage={(page) => update({ page }, false)} isShowingPageLength paginationDiv="col-sm-auto" paginationClass="pagination pagination-sm mb-0" />}</CardBody></Card></>}
    <DataModal value={selectedData} onClose={() => setSelectedData(undefined)} />
  </div></div>;
};
export default ImportLogDetail;
